# Generated by Django 2.1.3 on 2018-11-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.CharField(max_length=100, verbose_name='composition')),
                ('otherinfo', models.TextField(max_length=500, verbose_name='Other Info')),
                ('numberOfBoxes', models.IntegerField(verbose_name='Number of Boxes')),
                ('numberOfSamples', models.IntegerField(verbose_name='Number of Samples')),
                ('owner', models.CharField(max_length=100, verbose_name='Owner')),
                ('Telephone', models.CharField(max_length=12, verbose_name='telephone')),
                ('picture', models.ImageField(upload_to='uploads')),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
