# Generated by Django 2.1.3 on 2018-12-06 09:46

from django.db import migrations, models
import django.db.models.deletion
import storesample.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beamtime', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('pdffiles', models.FileField(upload_to='uploads/pdffiles')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samplename', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sample Name')),
                ('composition', models.CharField(max_length=100, verbose_name='composition')),
                ('otherinfo', models.TextField(blank=True, max_length=500, null=True, verbose_name='Other Info')),
                ('numberOfBoxes', models.IntegerField(default=1, verbose_name='Number of Boxes')),
                ('numberOfSamples', models.IntegerField(default=1, verbose_name='Number of Samples')),
                ('location', models.CharField(choices=[('Cabinet 1', 'Cabinet 1'), ('Cabinet 2', 'Cabinet 2'), ('Other', 'Other')], default='Cabinet 1', max_length=9)),
                ('temporarylocation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Temporarily at')),
                ('owner', models.CharField(max_length=100, verbose_name='Owner')),
                ('Telephone', models.CharField(max_length=12, verbose_name='telephone')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('origin', models.CharField(default='Unknown', max_length=100, verbose_name='Origin')),
                ('batch', models.CharField(default='Unknown', max_length=100, verbose_name='Batch')),
                ('beamtime', models.CharField(blank=True, max_length=100, null=True, verbose_name='Beamtime')),
                ('characterisation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Characterisation')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('instorage', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=9)),
                ('randomidentifier', models.CharField(default=storesample.models.generatecode, editable=False, max_length=5, verbose_name='idstring')),
            ],
        ),
        migrations.CreateModel(
            name='SampleCif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciffiles', models.FileField(upload_to='uploads/ciffiles')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storesample.Sample')),
            ],
        ),
        migrations.AddField(
            model_name='reports',
            name='samplereport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storesample.Sample'),
        ),
    ]
