# Generated by Django 2.1.3 on 2018-12-06 09:48

from django.db import migrations, models
import storesample.models


class Migration(migrations.Migration):

    dependencies = [
        ('storesample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='randomidentifier',
            field=models.CharField(default=storesample.models.generatecode, editable=False, max_length=5, unique=True, verbose_name='idstring'),
        ),
    ]
