# Generated by Django 2.1.3 on 2019-07-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storesample', '0002_auto_20181206_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='samplesmell',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sample Smell'),
        ),
    ]
