# Generated by Django 2.1.3 on 2018-11-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storesample', '0003_samplecif_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='instorage',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=9),
        ),
        migrations.AddField(
            model_name='sample',
            name='location',
            field=models.CharField(choices=[('Cabinet 1', 'Cabinet 1'), ('Cabinet 2', 'Cabinet 2')], default='Cabinet 1', max_length=9),
        ),
        migrations.AddField(
            model_name='sample',
            name='samplename',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sample Name'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='otherinfo',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Other Info'),
        ),
    ]
