# Generated by Django 3.2.12 on 2022-02-16 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storesample', '0003_sample_samplesmell'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionTemperatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.FloatField(verbose_name='Transition temperature in K')),
                ('TransitionType', models.CharField(choices=[('first', 'First Order'), ('second', 'SEcond Order'), ('unknown', 'N/A')], default='N/A', max_length=30, verbose_name='Transition Type')),
                ('OrderingType', models.CharField(choices=[('Antiferromagnetic', 'Antiferromagnetic'), ('Ferromagnetic', 'Ferromagnetic'), ('Ferrimagnetic', 'Ferrimagnetic'), ('Orbital Ordering', 'Orbital Ordering'), ('Charge Ordering', 'Charge Ordering'), ('N/A', 'N/A')], default='N/A', max_length=30, verbose_name='Ordering Type')),
                ('PropagationVector', models.JSONField(default=dict, verbose_name='Propagation Vector')),
                ('SampleTransitionTemperature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storesample.sample')),
            ],
        ),
    ]
