# Generated by Django 3.2.12 on 2022-02-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storesample', '0004_transitiontemperatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='urllink',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='LogBook available here'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='beamtime',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Beam time'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='pdffiles',
            field=models.FileField(blank=True, null=True, upload_to='uploads/pdffiles'),
        ),
    ]
