# Generated by Django 2.1.3 on 2018-11-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storesample', '0004_auto_20181128_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='batch',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='sample',
            name='beamtime',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Beamtime'),
        ),
        migrations.AddField(
            model_name='sample',
            name='characterisation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Characterisation'),
        ),
        migrations.AddField(
            model_name='sample',
            name='origin',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Origin'),
        ),
    ]
