# Generated by Django 2.1.3 on 2018-11-28 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storesample', '0005_auto_20181128_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beamtime', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('pdffiles', models.FileField(upload_to='uploads/pdffiles')),
                ('samplereport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storesample.Sample')),
            ],
        ),
    ]
