# Generated by Django 3.2.12 on 2022-02-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storesample', '0006_alter_transitiontemperatures_propagationvector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitiontemperatures',
            name='PropagationVector',
            field=models.JSONField(blank=True, default=dict, help_text='{"K1":"[1/2,1/2,1/2]"}', null=True, verbose_name='Propagation Vector'),
        ),
    ]
