# Generated by Django 3.2.12 on 2022-02-16 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storesample', '0007_alter_transitiontemperatures_propagationvector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='beamtime',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='samplesmell',
        ),
        migrations.CreateModel(
            name='SamplePictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picturefiles', models.FileField(upload_to='uploads/imagefiles')),
                ('picturesofthesample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storesample.sample')),
            ],
        ),
    ]
