# Generated by Django 3.2.12 on 2022-02-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storesample', '0008_auto_20220216_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='temporarylocation',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Temporarily at'),
        ),
    ]
